version: "3.4"

# Ancre pour réutiliser les variables d'environnement pour tous les services Baserow
x-backend-variables:
  &backend-variables
  SECRET_KEY: ${SECRET_KEY}
  BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL}
  DATABASE_URL: ${DATABASE_URL} 
  REDIS_URL: ${REDIS_URL} # On utilise l'URL complète du service Redis de Coolify
  # L'URL interne pour que les services se parlent entre eux
  PRIVATE_BACKEND_URL: http://backend:8000

services:
  backend:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    environment:
      <<: *backend-variables
    volumes:
      - media:/baserow/media

  web-frontend:
    image: baserow/web-frontend:1.34.2
    restart: unless-stopped
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL}
      PRIVATE_BACKEND_URL: http://backend:8000

  celery:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-worker
    environment:
      <<: *backend-variables
    volumes:
      - media:/baserow/media

  celery-export-worker:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-exportworker
    environment:
      <<: *backend-variables
    volumes:
      - media:/baserow/media

  celery-beat-worker:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-beat
    environment:
      <<: *backend-variables
    volumes:
      - media:/baserow/media

  volume-permissions-fixer:
    image: bash:4.4
    command: chown 9999:9999 -R /baserow/media
    volumes:
      - media:/baserow/media

volumes:
  media: # On garde uniquement le volume pour les fichiers uploadés
